In [1]:
import nltk 
from nltk.tokenize import word_tokenize 
from nltk.stem import PorterStemmer , WordNetLemmatizer 
from nltk.corpus import stopwords 
import re 
import pandas as pd

In [2]:
data= pd.read_csv('tripadvisor_hotel_reviews.csv') 
data.head()

                                              Review  Rating
0  nice hotel expensive parking got good deal sta...       4
1  ok nothing special charge diamond member hilto...       2
2  nice rooms not 4* experience hotel monaco seat...       3
3  unique, great stay, wonderful time hotel monac...       5
4  great stay great stay, went seahawk game aweso...       5

In [3]:
data['Review'][0]

'nice hotel expensive parking got good deal stay hotel anniversary, arrived late evening took advice previous reviews did valet parking, check quick easy, little disappointed non-existent view room room clean nice size, bed comfortable woke stiff neck high pillows, not soundproof like heard music room night morning loud bangs doors opening closing hear people talking hallway, maybe just noisy neighbors, aveda bath products nice, did not goldfish stay nice touch taken advantage staying longer, location great walking distance shopping, overall nice experience having pay 40 parking night,  '

In [4]:
data['lower_review']=data['Review'].str.lower() 
data.head()

,Review,Rating,lower_review
0,nice hotel expensive parking got good deal sta...,4,nice hotel expensive parking got good deal sta...
1,ok nothing special charge diamond member hilto...,2,ok nothing special charge diamond member hilto...
2,nice rooms not 4* experience hotel monaco seat...,3,nice rooms not 4* experience hotel monaco seat...
3,"unique, great stay, wonderful time hotel monac...",5,"unique, great stay, wonderful time hotel monac..."
4,"great stay great stay, went seahawk game aweso...",5,"great stay great stay, went seahawk game aweso..."

In [10]:
stop_word= stopwords.words('english') 
data['no_stopword_review']= data['lower_review'].apply(lambda x : " ".join([word for word in x.split() if word not in stop_word]))
data.head()

,Review,Rating,lower_review,no_stopword_review
0,nice hotel expensive parking got good deal sta...,4,nice hotel expensive parking got good deal sta...,nice hotel expensive parking got good deal sta...
1,ok nothing special charge diamond member hilto...,2,ok nothing special charge diamond member hilto...,ok nothing special charge diamond member hilto...
2,nice rooms not 4* experience hotel monaco seat...,3,nice rooms not 4* experience hotel monaco seat...,nice rooms 4* experience hotel monaco seattle ...
3,"unique, great stay, wonderful time hotel monac...",5,"unique, great stay, wonderful time hotel monac...","unique, great stay, wonderful time hotel monac..."
4,"great stay great stay, went seahawk game aweso...",5,"great stay great stay, went seahawk game aweso...","great stay great stay, went seahawk game aweso..."

In [12]:
data['no_*_review']= data.apply(lambda x : re.sub(r"[*]" , "star" , x['no_stopword_review']), axis=1 )
data.head()

,Review,Rating,lower_review,no_stopword_review,no_*_review
0,nice hotel expensive parking got good deal sta...,4,nice hotel expensive parking got good deal sta...,nice hotel expensive parking got good deal sta...,nice hotel expensive parking got good deal sta...
1,ok nothing special charge diamond member hilto...,2,ok nothing special charge diamond member hilto...,ok nothing special charge diamond member hilto...,ok nothing special charge diamond member hilto...
2,nice rooms not 4* experience hotel monaco seat...,3,nice rooms not 4* experience hotel monaco seat...,nice rooms 4* experience hotel monaco seattle ...,nice rooms 4star experience hotel monaco seatt...
3,"unique, great stay, wonderful time hotel monac...",5,"unique, great stay, wonderful time hotel monac...","unique, great stay, wonderful time hotel monac...","unique, great stay, wonderful time hotel monac..."
4,"great stay great stay, went seahawk game aweso...",5,"great stay great stay, went seahawk game aweso...","great stay great stay, went seahawk game aweso...","great stay great stay, went seahawk game aweso..."

In [13]:
data['no_punc_review']= data.apply(lambda x : re.sub(r"[^\w\s]" , "" , x['no_*_review']), axis=1 )
data.head()

,Review,Rating,lower_review,no_stopword_review,no_*_review,no_punc_review
0,nice hotel expensive parking got good deal sta...,4,nice hotel expensive parking got good deal sta...,nice hotel expensive parking got good deal sta...,nice hotel expensive parking got good deal sta...,nice hotel expensive parking got good deal sta...
1,ok nothing special charge diamond member hilto...,2,ok nothing special charge diamond member hilto...,ok nothing special charge diamond member hilto...,ok nothing special charge diamond member hilto...,ok nothing special charge diamond member hilto...
2,nice rooms not 4* experience hotel monaco seat...,3,nice rooms not 4* experience hotel monaco seat...,nice rooms 4* experience hotel monaco seattle ...,nice rooms 4star experience hotel monaco seatt...,nice rooms 4star experience hotel monaco seatt...
3,"unique, great stay, wonderful time hotel monac...",5,"unique, great stay, wonderful time hotel monac...","unique, great stay, wonderful time hotel monac...","unique, great stay, wonderful time hotel monac...",unique great stay wonderful time hotel monaco ...
4,"great stay great stay, went seahawk game aweso...",5,"great stay great stay, went seahawk game aweso...","great stay great stay, went seahawk game aweso...","great stay great stay, went seahawk game aweso...",great stay great stay went seahawk game awesom...

In [20]:
data['tokenized']=data.apply(lambda x : word_tokenize(x['no_punc_review']) , axis=1 )
data.head()

,Review,Rating,lower_review,no_stopword_review,no_*_review,no_punc_review,tokenized
0,nice hotel expensive parking got good deal sta...,4,nice hotel expensive parking got good deal sta...,nice hotel expensive parking got good deal sta...,nice hotel expensive parking got good deal sta...,nice hotel expensive parking got good deal sta...,"[nice, hotel, expensive, parking, got, good, d..."
1,ok nothing special charge diamond member hilto...,2,ok nothing special charge diamond member hilto...,ok nothing special charge diamond member hilto...,ok nothing special charge diamond member hilto...,ok nothing special charge diamond member hilto...,"[ok, nothing, special, charge, diamond, member..."
2,nice rooms not 4* experience hotel monaco seat...,3,nice rooms not 4* experience hotel monaco seat...,nice rooms 4* experience hotel monaco seattle ...,nice rooms 4star experience hotel monaco seatt...,nice rooms 4star experience hotel monaco seatt...,"[nice, rooms, 4star, experience, hotel, monaco..."
3,"unique, great stay, wonderful time hotel monac...",5,"unique, great stay, wonderful time hotel monac...","unique, great stay, wonderful time hotel monac...","unique, great stay, wonderful time hotel monac...",unique great stay wonderful time hotel monaco ...,"[unique, great, stay, wonderful, time, hotel, ..."
4,"great stay great stay, went seahawk game aweso...",5,"great stay great stay, went seahawk game aweso...","great stay great stay, went seahawk game aweso...","great stay great stay, went seahawk game aweso...",great stay great stay went seahawk game awesom...,"[great, stay, great, stay, went, seahawk, game..."

In [23]:
ps=PorterStemmer()
data['stemmed'] = data['tokenized'].apply (lambda tokens  : [ps.stem(token) for token in tokens])
data.head()

,Review,Rating,lower_review,no_stopword_review,no_*_review,no_punc_review,tokenized,stemmed
0,nice hotel expensive parking got good deal sta...,4,nice hotel expensive parking got good deal sta...,nice hotel expensive parking got good deal sta...,nice hotel expensive parking got good deal sta...,nice hotel expensive parking got good deal sta...,"[nice, hotel, expensive, parking, got, good, d...","[nice, hotel, expens, park, got, good, deal, s..."
1,ok nothing special charge diamond member hilto...,2,ok nothing special charge diamond member hilto...,ok nothing special charge diamond member hilto...,ok nothing special charge diamond member hilto...,ok nothing special charge diamond member hilto...,"[ok, nothing, special, charge, diamond, member...","[ok, noth, special, charg, diamond, member, hi..."
2,nice rooms not 4* experience hotel monaco seat...,3,nice rooms not 4* experience hotel monaco seat...,nice rooms 4* experience hotel monaco seattle ...,nice rooms 4star experience hotel monaco seatt...,nice rooms 4star experience hotel monaco seatt...,"[nice, rooms, 4star, experience, hotel, monaco...","[nice, room, 4star, experi, hotel, monaco, sea..."
3,"unique, great stay, wonderful time hotel monac...",5,"unique, great stay, wonderful time hotel monac...","unique, great stay, wonderful time hotel monac...","unique, great stay, wonderful time hotel monac...",unique great stay wonderful time hotel monaco ...,"[unique, great, stay, wonderful, time, hotel, ...","[uniqu, great, stay, wonder, time, hotel, mona..."
4,"great stay great stay, went seahawk game aweso...",5,"great stay great stay, went seahawk game aweso...","great stay great stay, went seahawk game aweso...","great stay great stay, went seahawk game aweso...",great stay great stay went seahawk game awesom...,"[great, stay, great, stay, went, seahawk, game...","[great, stay, great, stay, went, seahawk, game..."

In [27]:
lemmatizer=WordNetLemmatizer() 
data['lemmatized']= data['stemmed'].apply (lambda  tokens : [lemmatizer.lemmatize(token) for token in tokens] )
data.head()

,Review,Rating,lower_review,no_stopword_review,no_*_review,no_punc_review,tokenized,stemmed,lemmatized
0,nice hotel expensive parking got good deal sta...,4,nice hotel expensive parking got good deal sta...,nice hotel expensive parking got good deal sta...,nice hotel expensive parking got good deal sta...,nice hotel expensive parking got good deal sta...,"[nice, hotel, expensive, parking, got, good, d...","[nice, hotel, expens, park, got, good, deal, s...","[nice, hotel, expens, park, got, good, deal, s..."
1,ok nothing special charge diamond member hilto...,2,ok nothing special charge diamond member hilto...,ok nothing special charge diamond member hilto...,ok nothing special charge diamond member hilto...,ok nothing special charge diamond member hilto...,"[ok, nothing, special, charge, diamond, member...","[ok, noth, special, charg, diamond, member, hi...","[ok, noth, special, charg, diamond, member, hi..."
2,nice rooms not 4* experience hotel monaco seat...,3,nice rooms not 4* experience hotel monaco seat...,nice rooms 4* experience hotel monaco seattle ...,nice rooms 4star experience hotel monaco seatt...,nice rooms 4star experience hotel monaco seatt...,"[nice, rooms, 4star, experience, hotel, monaco...","[nice, room, 4star, experi, hotel, monaco, sea...","[nice, room, 4star, experi, hotel, monaco, sea..."
3,"unique, great stay, wonderful time hotel monac...",5,"unique, great stay, wonderful time hotel monac...","unique, great stay, wonderful time hotel monac...","unique, great stay, wonderful time hotel monac...",unique great stay wonderful time hotel monaco ...,"[unique, great, stay, wonderful, time, hotel, ...","[uniqu, great, stay, wonder, time, hotel, mona...","[uniqu, great, stay, wonder, time, hotel, mona..."
4,"great stay great stay, went seahawk game aweso...",5,"great stay great stay, went seahawk game aweso...","great stay great stay, went seahawk game aweso...","great stay great stay, went seahawk game aweso...",great stay great stay went seahawk game awesom...,"[great, stay, great, stay, went, seahawk, game...","[great, stay, great, stay, went, seahawk, game...","[great, stay, great, stay, went, seahawk, game..."

In [28]:
cleaning = sum(data['lemmatized'],[]) 
unigrams_1=(pd.Series(nltk.ngrams(cleaning , 1)).value_counts())
print(unigrams_1)

(hotel,)       292
(room,)        275
(stay,)        160
(great,)       126
(staff,)        90
              ...
(idea,)          1
(250night,)      1
(affect,)        1
(175,)           1
(slipper,)       1
Name: count, Length: 2274, dtype: int64

In [29]:
bigrams_1=(pd.Series(nltk.ngrams(cleaning , 2)).value_counts())
print(bigrams_1)

(great, locat)       24
(space, needl)       21
(hotel, monaco)      16
(stay, hotel)        15
(staff, friendli)    13
                     ..
(start, minut)        1
(room, start)         1
(chang, 3)            1
(warwick, chang)      1
(food, raffl)         1
Name: count, Length: 8051, dtype: int64

In [30]:
trigrams_1=(pd.Series(nltk.ngrams(cleaning , 3)).value_counts())
print(trigrams_1)

(pike, place, market)        8
(view, space, needl)         5
(staff, friendli, help)      5
(hotel, great, locat)        5
(stay, crown, plaza)         5
                            ..
(central, seattl, handi)     1
(travel, central, seattl)    1
(free, travel, central)      1
(cheap, free, travel)        1
(hotel, right, street)       1
Name: count, Length: 9155, dtype: int64